FROM ubuntu 

RUN apt-get update && apt-get install -y curl

RUN apt install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common

RUN curl -fsSL https://download.docker.com/linux/debian/gpg |  apt-key add -

RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu  bionic stable"  

RUN apt-get update 

RUN apt install -y  docker-ce 

RUN apt-get install -y libssl-dev  

RUN apt-get install -y  python-dev libffi-dev  gcc linux-libc-dev  make

RUN apt install -y python3-pip  

RUN pip3 install docker-compose

COPY hello.sh .

CMD tail -f /dev/null
